info:
  app:
    name: 'ConstruyeSmart'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'

grails:
  profile: web
  codegen:
    defaultPackage: com.example
  spring:
    transactionManagement:
      proxies: false
  mongo:
    url: mongodb://localhost:27017/construyesmart
    options:
      autoIndexCreation: true
      retryWrites: true
      w: majority
  gorm:
    mongodb:
      url: mongodb://localhost:27017/construyesmart
      options:
        autoIndexCreation: true
        retryWrites: true
        w: majority
    default:
      mapping:
        datasource: mongodb
  plugin:
    springsecurity:
      userLookup:
        userDomainClassName: 'com.example.User'
        authorityJoinClassName: 'com.example.UserRole'
      authority:
        className: 'com.example.Role'
      password:
        algorithm: 'bcrypt'
        bcrypt:
          logrounds: 10
      filterChain:
        chainMap:
          - pattern: '/assets/**'
            filters: 'none'
          - pattern: '/**/js/**'
            filters: 'none'
          - pattern: '/**/css/**'
            filters: 'none'
          - pattern: '/**/images/**'
            filters: 'none'
          - pattern: '/**/favicon.ico'
            filters: 'none'
          - pattern: '/login/**'
            filters: 'none'
          - pattern: '/logout/**'
            filters: 'none'
          - pattern: '/user/create'
            filters: 'none'
          - pattern: '/user/save'
            filters: 'none'
          - pattern: '/user/createAdmin'
            filters: 'none'
          - pattern: '/**'
            filters: 'JOINED_FILTERS'
      controllerAnnotations:
        staticRules:
          - pattern: '/'
            access: ['permitAll']
          - pattern: '/error'
            access: ['permitAll']
          - pattern: '/index'
            access: ['permitAll']
          - pattern: '/index.gsp'
            access: ['permitAll']
          - pattern: '/shutdown'
            access: ['permitAll']
          - pattern: '/assets/**'
            access: ['permitAll']
          - pattern: '/**/js/**'
            access: ['permitAll']
          - pattern: '/**/css/**'
            access: ['permitAll']
          - pattern: '/**/images/**'
            access: ['permitAll']
          - pattern: '/**/favicon.ico'
            access: ['permitAll']
          - pattern: '/login/**'
            access: ['permitAll']
          - pattern: '/logout/**'
            access: ['permitAll']
          - pattern: '/user/create'
            access: ['permitAll']
          - pattern: '/user/save'
            access: ['permitAll']
          - pattern: '/user/createAdmin'
            access: ['permitAll']
          - pattern: '/home/**'
            access: ['ROLE_USER', 'ROLE_ADMIN']
      logout:
        postOnly: false
      successHandler:
        defaultTargetUrl: '/home/index'
      failureHandler:
        defaultFailureUrl: '/login/auth?login_error=1'
        ajaxAuthenticationFailureUrl: '/login/authAjax?login_error=1'
      apf:
        storeLastUsername: true
      rejectIfNoRule: false
      fii:
        rejectPublicInvocations: false

hibernate:
  default:
    datasource: mongodb

server:
  port: 8080
  servlet:
    context-path: /

spring:
  main:
    banner-mode: "off"
  application:
    name: construyesmart
  data:
    mongodb:
      uri: mongodb://localhost:27017/construyesmart
      auto-index-creation: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  security:
    user:
      name: admin
      password: admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password

environments:
    development:
        grails:
            mongodb:
                url: mongodb://localhost:27017/construyesmart
                options:
                    autoIndexCreation: true
                    retryWrites: true
                    w: majority
    test:
        grails:
            mongodb:
                url: mongodb://localhost:27017/construyesmart_test
    production:
        grails:
            mongodb:
                url: mongodb://localhost:27017/construyesmart_prod

grails.mime:
  disable:
    accept:
      header:
        userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
  types:
    all: '*/*'
    atom: application/atom+xml
    css: text/css
    csv: text/csv
    form: application/x-www-form-urlencoded
    html:
      - text/html
      - application/xhtml+xml
    js: text/javascript
    json:
      - application/json
      - text/json
    multipartForm: multipart/form-data
    pdf: application/pdf
    rss: application/rss+xml
    text: text/plain
    hal:
      - application/hal+json
      - application/hal+xml
    xml:
      - text/xml
      - application/xml

grails.urlmapping:
  cache:
    maxsize: 1000

grails.controllers:
  defaultScope: singleton

grails.converters:
  encoding: UTF-8

grails.views:
  default:
    codec: html
  gsp:
    encoding: UTF-8
    htmlcodec: xml
    codecs:
      expression: html
      scriptlets: html
      taglib: none
      staticparts: none

api:
    google:
        maps:
            key: ${GOOGLE_MAPS_API_KEY}
    openweathermap:
        key: ${OPENWEATHERMAP_API_KEY}
    youtube:
        key: ${YOUTUBE_API_KEY}
    homedepot:
        key: ${HOME_DEPOT_API_KEY}
